/**
 * tools/reporter.js
 * Generate reports and documents in various formats.
 *
 * Saves reports to the workspace docs/ directory.
 * Returns the file path and a preview of the content.
 */

import fs    from 'fs';
import path  from 'path';
import { config } from '../config/config.js';
import { logger  } from '../utils/logger.js';

const DOCS_DIR = path.join(config.agent.workspaceDir, 'docs');

export class Reporter {
  constructor() {
    // Ensure docs directory exists
    fs.mkdirSync(DOCS_DIR, { recursive: true });
  }

  // ─────────────────────────────────────────────────────────────
  // Public API
  // ─────────────────────────────────────────────────────────────

  /**
   * Save a report to disk and return a summary.
   * @param {object} opts
   * @param {string} opts.title    – Report title
   * @param {string} opts.content  – Full markdown content
   * @param {string} [opts.filename] – Override the auto-generated filename
   * @returns {Promise<string>} – Result message with file path & preview
   */
  async save({ title = 'Report', content = '', filename } = {}) {
    const slug      = this._slugify(title);
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
    const fname     = filename || `${slug}_${timestamp}.md`;
    const filePath  = path.join(DOCS_DIR, fname);

    // Prepend title + timestamp if not already present
    const fullContent = this._ensureHeader(title, content);

    fs.writeFileSync(filePath, fullContent, 'utf8');
    logger.info(`[Reporter] Saved report: ${filePath}`);

    const preview = fullContent.split('\n').slice(0, 10).join('\n');
    return [
      `📄 *Report saved!*`,
      `📁 \`${filePath}\``,
      ``,
      `*Preview:*`,
      `\`\`\``,
      preview,
      `...\`\`\``,
    ].join('\n');
  }

  /**
   * List all previously generated reports.
   * @returns {string}
   */
  listReports() {
    fs.mkdirSync(DOCS_DIR, { recursive: true });
    const files = fs.readdirSync(DOCS_DIR)
      .filter((f) => f.endsWith('.md'))
      .sort()
      .reverse()
      .slice(0, 20);

    if (!files.length) return '📂 No reports found yet.';

    const lines = ['*Recent Reports:*', ''];
    files.forEach((f, i) => {
      const stat    = fs.statSync(path.join(DOCS_DIR, f));
      const size    = (stat.size / 1024).toFixed(1);
      const modDate = stat.mtime.toLocaleString();
      lines.push(`${i + 1}. \`${f}\` – ${size} KB – ${modDate}`);
    });
    return lines.join('\n');
  }

  /**
   * Read and return the content of a specific report.
   * @param {string} fname
   * @returns {string}
   */
  readReport(fname) {
    const filePath = path.join(DOCS_DIR, fname);
    if (!fs.existsSync(filePath)) return `❌ Report not found: ${fname}`;
    const content = fs.readFileSync(filePath, 'utf8');
    return content.slice(0, 4000); // Telegram message limit protection
  }

  // ─────────────────────────────────────────────────────────────
  // Private helpers
  // ─────────────────────────────────────────────────────────────

  _slugify(str) {
    return str
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, '')
      .trim()
      .replace(/\s+/g, '_')
      .slice(0, 40);
  }

  _ensureHeader(title, content) {
    const trimmed = content.trim();
    // If content already starts with a heading, leave it
    if (trimmed.startsWith('#')) return trimmed + '\n';

    const timestamp = new Date().toLocaleString();
    return [
      `# ${title}`,
      ``,
      `*Generated by ClawBot on ${timestamp}*`,
      ``,
      `---`,
      ``,
      trimmed,
      ``,
    ].join('\n');
  }
}
